[build-system]
requires = ["setuptools >= 58.0"]
build-backend = "setuptools.build_meta"

[project]
name = "solve-x-questions"
version = "0.1"
dependencies = ["pymongo", "requests", "fastapi", "uvicorn"]
requires-python = ">= 3.10"
